FROM python:3.11.1-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTCODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.6.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_CREATE=false

ENV PATH="$PATH:$POETRY_HOME/bin"

# criando o usuario app para não usar o usuario root
RUN groupadd app && useradd -g app app
RUN pip install -U pip
RUN apt update && apt upgrade -y && apt install --no-install-recommends -y curl
RUN curl -sSL https://install.python-poetry.org | python3 -
WORKDIR /home/api
COPY . /home/api

# ENV VIRTUAL_ENV=/opt/venv
# RUN python3 -m venv $VIRTUAL_ENV
# ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN poetry install 

# definindo o pwner do diretorio
RUN chown -R app:app /home/api
USER app
EXPOSE 8000
CMD [ "poetry", "run", "uvicorn", "--reload", "todo.app:app", "--host=0.0.0.0", "--port=8000" ]