"""teste

Revision ID: 99b06a755b1a
Revises: 67faedd1a399
Create Date: 2023-08-03 18:04:06.518793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '99b06a755b1a'
down_revision = '67faedd1a399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
