[default]
 
[default.db]
uri = ''
connect_args = {check_same_thread=false}
echo = false

[default.security]
# Set secret key_in .secrets.toml
# SECRET_KEY = ""
ALGORITHM = "HS256"
ACCES_TOKEN_EXPIRE_MINUTES = 20
REFRESH_TOKEN_EXPIRE_MINUTES = 600
